config/routes.rb
Hosting::Application.routes.draw do
  resources :customers
  root to: 'dashboard#index'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  default_scope order: :expiration_date
  attr_accessible :expiration_date, :name, :notes
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    redirect_to root_path
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(params[:customer])
    if @customer.save
      redirect_to root_path, notice: "#{@customer.name} has been created."
    else
      flash[:error] = "Customer could not be created."
      render :new
    end
  end

  def edit
    @customer = Customer.find_by_id(params[:id])
    unless @customer
      redirect_to root_path
    end
  end

  def update
    @customer = Customer.find_by_id(params[:id])
    if @customer.update_attributes(params[:customer])
      flash[:notice] = "#{@customer.name} has been updated."
      redirect_to root_path
    else
      flash[:error] = "Customer could not be updated."
      render :edit
    end
  end

  def show
    @customer = Customer.find_by_id(params[:id])
  end

  def destroy
    @customer = Customer.find_by_id(params[:id])
    flash[:notice] = 'Customer has been deleted.' if @customer.destroy
    redirect_to root_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @customers = Customer.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_date(date)
    date.to_formatted_s(:long)
  end

  def format_month_day(date)
    date.strftime("%b. %d")
  end

  def format_year(date)
    date.year
  end

  def days_until(date, options = {})
    options[:include_label] = true if options[:include_label].nil?
    days = (date - Date.today).to_i
    if options[:include_label]
      "#{days} #{days_until_label date}"
    else
      "#{days}"
    end
  end

  def days_until_label(date)
    days = (date - Date.today).to_i
    days == 1 ? 'day' : 'days'
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/customers/_form.html.haml
%div.rows
  %div.row
    = label :customer, :name, 'Customer name'
    = text_field :customer, :name
  %div.row
    = label :customer, :expiration_date, "Expiration date <em>(Optional)</em>".html_safe
    = text_field :customer, :expiration_date, type: 'date', size: nil
  %div.row
    = label :customer, :notes, "Notes <em>(Optional)</em>".html_safe
    = text_area :customer, :notes, cols: 60, rows: 4

app/views/customers/edit.html.haml
%h2 Edit customer
= form_for @customer do
  = render 'form'
  .row
    = submit_tag 'Save'
    or 
    = link_to 'Cancel', root_path

app/views/customers/new.html.haml
%h2 Add customer
= form_for @customer do
  = render 'form'
  .row
    = submit_tag 'Save'
    or 
    = link_to 'Cancel', root_path

app/views/dashboard/index.html.haml
.customers
  - @customers.each do |customer|
    %section.customer{id: "customer_#{customer.id}", class: cycle('odd', 'even')}
      - if customer.expiration_date
        %div.expiration
          %div.days
            %div.value= days_until customer.expiration_date, include_label: false
            %div.label= days_until_label customer.expiration_date
          %div.date
            %div.value= format_month_day customer.expiration_date
            %div.label= format_year customer.expiration_date
      %h2= customer.name
      %div.notes= customer.notes
      %nav
        = link_to 'Edit', edit_customer_path(customer)
        = link_to 'Delete', customer_path(customer), method: 'delete', data: {confirm: 'Are you sure? This cannot be undone.'}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Hosting for Farfromrest
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tags
%body
  %div#wrapper
    %header
      %nav
        = link_to 'Add customer', new_customer_path
      %h1
        = link_to 'Hosting for Farfromrest', root_path
    %div#main
      - if flash[:notice]
        %div.flash.notice
          = flash[:notice]
      - if flash[:error]
        %div.flash.error
          = flash[:error]
      = yield
    %footer
      %p= "&copy; #{Date.today.year} <a href=\"http://www.farfromrest.com\">Farfromrest Web Development, Inc.</a>".html_safe
  = javascript_include_tag "application"